### ISSUE TITLE
window.onmousewheel event.deltaY can be something other than int.

### ISSUE THREAD

**Issue by LuisMars** [nkast/Wasm#5]
I'm getting this error when scrolling

```
Error: The JSON value could not be converted to System.Int32. Path: $ | LineNumber: 0 | BytePositionInLine: 17.
    at Jn (https://localhost:7234/_framework/dotnet.runtime.8.0.0.lsg2dbrz1d.js:3:31614)
    at kr (https://localhost:7234/_framework/dotnet.runtime.8.0.0.lsg2dbrz1d.js:3:35529)
    at Object.<anonymous> (https://localhost:7234/_framework/dotnet.runtime.8.0.0.lsg2dbrz1d.js:3:180449)
    at Object.invokeDotNetFromJS (https://localhost:7234/_framework/blazor.webassembly.js:1:45082)
    at g.invokeDotNetMethod (https://localhost:7234/_framework/blazor.webassembly.js:1:3485)
    at g.invokeDotNetStaticMethod (https://localhost:7234/_framework/blazor.webassembly.js:1:3241)
    at e.invokeMethod (https://localhost:7234/_framework/blazor.webassembly.js:1:1980)
    at RegisterEvents.window.onmousewheel (https://localhost:7234/_content/nkast.Wasm.Dom/js/Window.6.0.5.js:57:20)
```
https://github.com/nkast/Wasm/blob/195f0e9da17daba116946dca826304c5d5665515/Wasm.Dom/wwwroot/js/Window.6.0.5.js#L58

It can be solved it by removing the decimal part, but I'm not sure what's the proper way to fix it.

```
window.onmousewheel = function (event) {
    DotNet.invokeMethod('nkast.Wasm.Dom', 'JsWindowOnMouseWheel', uid,
        event.deltaX | 0, event.deltaY | 0, event.deltaZ | 0, event.deltaMode | 0);
};
```

**Comment by nkast** [comment]
@LuisMars , On what browser you get that error?

references:
https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event

https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event

**Comment by LuisMars** [comment]
I was getting it on Chrome, on Firefox the wheel is not even working

**Comment by nkast** [comment]
I've tested both of the samples that are in this repo, with the latest .net6 packages and .net8 v8.0.0 & v8.0.2.
I am sorry, I can't replicate this.

**Comment by nkast** [comment]
I saw this on Desktop Chrome when in Mobile simulation in DevTools. DeltaX had a value of -0.
Normal Chrome window worked fine.

fixed in https://github.com/nkast/Wasm/commit/514e2957269d602bae069d723b1882c91053bd4f
